e2e:
  scene_name: at-api
  # retry config
  retry:
    max: 5
    interval: 10s
    total_timeout: 10m
  # services in docker-compose
  modules:
    # provider service
    providers:
      - name: at-api
        docker_service:
          hostname: at-api
          restart: on-failure
          container_name: test
          depends_on:
            mysql:
              condition: service_healthy
            seata-server:
              condition: service_healthy
          environment:
            E2E_ENV: true
            jdbc.account.url: jdbc:mysql://127.0.0.1:3306/seata?useSSL=false&serverTimezone=UTC
            jdbc.account.username: user
            jdbc.account.password: 123456
            jdbc.stock.url: jdbc:mysql://127.0.0.1:3306/seata?useSSL=false&serverTimezone=UTC
            jdbc.stock.username: user
            jdbc.stock.password: 123456
            jdbc.order.url: jdbc:mysql://127.0.0.1:3306/seata?useSSL=false&serverTimezone=UTC
            jdbc.order.username: user
            jdbc.order.password: 123456
    # infrastructure services
    infrastructures:
      - name: mysql
        docker_service:
          hostname: mysqlAddress
          image: mysql:5.7
          volumes:
            - ./e2e-files/sqlsh:/docker-entrypoint-initdb.d
          restart: always
          environment:
            MYSQL_ROOT_PASSWORD: 123456
            MYSQL_DATABASE: seata
            MYSQL_USER: user
            MYSQL_PASSWORD: 123456
          healthcheck:
            test: '[ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]'
            interval: 5s
            timeout: 10s
            retries: 10
      - name: seata-server
        docker_service:
          hostname: seata
          image: seataio/seata-server:2.0.0
          environment:
            SEATA_PORT: 8091
            STORE_MODE: file

  # cases to verify
  cases:
    - name: normal test (commit or rollback)
      invoke: 'docker exec test cat result.yaml'
      verify: './e2e-files/rollback.yaml'